CREATE TABLE "mytable" (
  "CREATE TABLE "ADMIN"" text
);

INSERT INTO "mytable" ("CREATE TABLE "ADMIN"")
VALUES
('(	"ADMIN_ID" NUMBER(*'),
('"USER_ID" NUMBER(*'),
('CONSTRAINT "PK_ADMIN_ID" PRIMARY KEY ("ADMIN_ID")'),
('USING INDEX  ENABLE'),
(') ;'),
('ALTER TABLE "ADMIN" ADD CONSTRAINT "FK_ADMIN_ID" FOREIGN KEY ("USER_ID")'),
('REFERENCES "CLECK_USER" ("USER_ID") ON DELETE CASCADE ENABLE;'),
('CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN_TRG"'),
('BEFORE INSERT ON ADMIN'),
('FOR EACH ROW'),
('BEGIN'),
('IF :NEW.admin_id IS NULL THEN'),
('SELECT seq_admin.NEXTVAL INTO :NEW.admin_id FROM SYS.DUAL;'),
('END IF;'),
('END;'),
('/'),
('ALTER TRIGGER "ADMIN_TRG" ENABLE;');
