CREATE TABLE "mytable" (
  "SELECT USER_TYPE FROM CLECK_USER WHERE UPPER(USER_EMAIL) = V('APP_USER') AND USER_TYPE IN ('Trader')" text
);

INSERT INTO "mytable" ("SELECT USER_TYPE FROM CLECK_USER WHERE UPPER(USER_EMAIL) = V('APP_USER') AND USER_TYPE IN ('Trader')")
VALUES
;
