CREATE TABLE "mytable" (
  "authentication for admin" text
);

INSERT INTO "mytable" ("authentication for admin")
VALUES
('FUNCTION AUTH'),
('(p_username IN VARCHAR2'),
('p_password IN VARCHAR2)'),
('RETURN BOOLEAN'),
('IS'),
('l_useremail     VARCHAR2(255) := UPPER(p_username);'),
('l_user_password VARCHAR2(255);'),
('l_user_role     VARCHAR2(255);'),
('BEGIN'),
('-- Check if email and password are provided'),
('IF p_username IS NULL OR p_username = '''' OR p_password IS NULL OR p_password = '''' THEN'),
('RAISE_APPLICATION_ERROR(-20005'),
('END IF;'),
('BEGIN'),
('-- Fetch password and role from DB'),
('SELECT'),
('USER_PASSWORD'),
('USER_TYPE'),
('INTO'),
('l_user_password'),
('l_user_role'),
('FROM'),
('CLECK_USER'),
('WHERE'),
('UPPER(USER_EMAIL) = l_useremail;'),
('-- Compare directly with plain text'),
('IF l_user_password != p_password THEN'),
('RAISE_APPLICATION_ERROR(-20002'),
('END IF;'),
('-- Check for Admin role'),
('IF UPPER(l_user_role) != ''ADMIN'' THEN'),
('RETURN FALSE;'),
('END IF;'),
('-- All checks passed'),
('RETURN TRUE;'),
('EXCEPTION'),
('WHEN NO_DATA_FOUND THEN'),
('RAISE_APPLICATION_ERROR(-20001'),
('END;'),
('EXCEPTION'),
('WHEN OTHERS THEN'),
('RETURN FALSE;'),
('END AUTH;');
